final List<Map<String, dynamic>> logements = [
  {
    'id': '001',
    'titre': 'Chambre moderne à Fidjrossè',
    'bailleur': 'Rosine Hounkpatin',
    'prix': 30000,
    'statut': 'Disponible',
    'type': 'Chambre',
    'adresse': 'Fidjrossè Plage, Cotonou',
    'dateAjout': '2024-06-15',
    'images': 2,
  },
  {
    'id': '002',
    'titre': 'Studio meublé à Akpakpa',
    'bailleur': 'Mathieu Agbangla',
    'prix': 70000,
    'statut': 'Réservé',
    'type': 'Studio',
    'adresse': 'Akpakpa Dodomey, Cotonou',
    'dateAjout': '2024-06-12',
    'images': 4,
  },
  {
    'id': '003',
    'titre': 'Appartement 2 pièces à Calavi',
    'bailleur': 'Clarisse Adéchian',
    'prix': 95000,
    'statut': 'Disponible',
    'type': 'Appartement',
    'adresse': 'Tankpè, Abomey-Calavi',
    'dateAjout': '2024-06-10',
    'images': 3,
  },
  {
    'id': '004',
    'titre': 'Chambre avec douche interne',
    'bailleur': 'Ismaël Bio Tchané',
    'prix': 25000,
    'statut': 'En attente',
    'type': 'Chambre',
    'adresse': 'Gbèdjromèdé, Cotonou',
    'dateAjout': '2024-06-08',
    'images': 2,
  },
  {
    'id': '005',
    'titre': 'Studio climatisé proche UAC',
    'bailleur': 'Florent Toko',
    'prix': 80000,
    'statut': 'Disponible',
    'type': 'Studio',
    'adresse': 'Zogbadjè, Abomey-Calavi',
    'dateAjout': '2024-06-05',
    'images': 5,
  },
  {
    'id': '006',
    'titre': 'Appartement haut standing à Porto-Novo',
    'bailleur': 'Esther Avodagbé',
    'prix': 130000,
    'statut': 'Réservé',
    'type': 'Appartement',
    'adresse': 'Quartier Ouando, Porto-Novo',
    'dateAjout': '2024-06-01',
    'images': 6,
  },
];
