import 'package:iconsax/iconsax.dart';

final List<Map<String, dynamic>> reservations = [
  {
    'id': 'RES001',
    'etudiant': 'Carmel Dossou',
    'logement': 'Studio meublé - Zogbadjè',
    'proprietaire': 'Ismael Adéchian',
    'dateReservation': '2024-06-20',
    'dateDebut': '2024-07-01',
    'dateFin': '2024-12-31',
    'montant': 50000,
    'statut': 'Confirmée',
    'avatar': Iconsax.user,
  },
  {
    'id': 'RES002',
    'etudiant': 'Cyrille Hounkpè',
    'logement': 'Appartement 2 pièces - Akpakpa',
    'proprietaire': 'Viviane Tchokpon',
    'dateReservation': '2024-06-21',
    'dateDebut': '2024-07-10',
    'dateFin': '2024-12-31',
    'montant': 65000,
    'statut': 'En attente',
    'avatar': Iconsax.user,
  },
  {
    'id': 'RES003',
    'etudiant': 'Séverine Houngnibo',
    'logement': 'Chambre simple - Porto-Novo',
    'proprietaire': 'Flavien Gbaguidi',
    'dateReservation': '2024-06-22',
    'dateDebut': '2024-08-01',
    'dateFin': '2024-12-31',
    'montant': 20000,
    'statut': 'Annulée',
    'avatar': Iconsax.user,
  },
  {
    'id': 'RES004',
    'etudiant': 'Wilfried Agossou',
    'logement': 'Studio - Fidjrossè',
    'proprietaire': 'Edwige Avodagbé',
    'dateReservation': '2024-06-23',
    'dateDebut': '2024-07-05',
    'dateFin': '2024-12-31',
    'montant': 55000,
    'statut': 'Confirmée',
    'avatar': Iconsax.user,
  },
  {
    'id': 'RES005',
    'etudiant': 'Joséphine Kpatcha',
    'logement': 'Appartement meublé - Tankpè',
    'proprietaire': 'Romuald Tokoudagba',
    'dateReservation': '2024-06-24',
    'dateDebut': '2024-07-15',
    'dateFin': '2024-12-31',
    'montant': 70000,
    'statut': 'En attente',
    'avatar': Iconsax.user,
  },
  {
    'id': 'RES006',
    'etudiant': 'Fabrice Bio Tchané',
    'logement': 'Chambre - Gbèdjromèdé',
    'proprietaire': 'Nadine Houngbédji',
    'dateReservation': '2024-06-25',
    'dateDebut': '2024-08-01',
    'dateFin': '2024-12-31',
    'montant': 25000,
    'statut': 'Confirmée',
    'avatar': Iconsax.user,
  },
];
