final List<Map<String, dynamic>> utilisateurs = [
  {
    'id': '001',
    'nom': 'Brice Hounkpè',
    'email': 'brice.hounkpe@uniben.bj',
    'type': 'Bailleur',
    'telephone': '+229 97 45 62 10',
    'dateInscription': '2024-06-14',
    'statut': 'Actif',
    'logements': 4,
  },
  {
    'id': '002',
    'nom': 'Dora Avodagbé',
    'email': 'dora.avodagbe@etudiant.bj',
    'type': 'Étudiant',
    'telephone': '+229 61 23 45 67',
    'dateInscription': '2024-06-10',
    'statut': 'Actif',
    'reservations': 2,
  },
  {
    'id': '003',
    'nom': 'Roméo Adéchian',
    'email': 'romeo.adechian@gmail.com',
    'type': 'Bailleur',
    'telephone': '+229 91 12 78 45',
    'dateInscription': '2024-06-05',
    'statut': 'Suspendu',
    'logements': 1,
  },
  {
    'id': '004',
    'nom': 'Séverine Gbaguidi',
    'email': 'severine.gbaguidi@etudiant.uac.bj',
    'type': 'Étudiant',
    'telephone': '+229 67 88 11 22',
    'dateInscription': '2024-06-03',
    'statut': 'Actif',
    'reservations': 1,
  },
  {
    'id': '005',
    'nom': 'André Tokoudagba',
    'email': 'andre.tokou@gestimob.bj',
    'type': 'Bailleur',
    'telephone': '+229 95 66 77 88',
    'dateInscription': '2024-05-29',
    'statut': 'Actif',
    'logements': 3,
  },
  {
    'id': '006',
    'nom': 'Clarisse Houngnibo',
    'email': 'clarisse.houngnibo@etud.bj',
    'type': 'Étudiant',
    'telephone': '+229 69 00 11 22',
    'dateInscription': '2024-05-26',
    'statut': 'Suspendu',
    'reservations': 0,
  },
];
